export const phaseData = [
  {
    phaseId: 'c874b55a-53c4-45ec-8da9-ca7881c20978',
    phaseName: 'New & Unassigned',
    delayed: '2',
    onTrack: '4',
  },
  {
    phaseId: '10295d6a-01cc-41ac-abec-4c2d034981de',
    phaseName: 'Kick-off',
    delayed: '1',
    onTrack: '3',
  },
  {
    phaseId: 'bea0cbda-e8a8-4b49-a2c2-f08fa99deaa8',
    phaseName: 'Landlord Works',
    delayed: '5',
    onTrack: '4',
  },
  {
    phaseId: '4128a84c-5b49-4920-a7e5-8a3656aea8b0',
    phaseName: 'Design',
    delayed: '0',
    onTrack: '0',
  },
  {
    phaseId: 'e3244a52-df1d-4492-a9ab-9fee2986c920',
    phaseName: 'Unit Handover & Fitout',
    delayed: '4',
    onTrack: '4',
  },
  {
    phaseId: 'b38fd151-257a-4d79-a5d7-a43ac2574f2c',
    phaseName: 'Unit Opening',
    delayed: '1',
    onTrack: '0',
  },
  {
    phaseId: '88b97ca7-ae29-48e1-a5cd-991b2336e8d1',
    phaseName: 'Closure',
    delayed: '0',
    onTrack: '1',
  },
  {
    phaseId: '8',
    phaseName: 'On Hold',
    delayed: '0',
    onTrack: '0',
    onHold: '3',
  },
];

export const caseListDetails = [
  {
    id: '828815ed-534c-4ace-a08c-303ec2cc95f9',
    caseNo: '123456789',
    property: 'The Mall of UAE',
    tenant: 'Landmark (Centerpoint)',
    units: 'L1-11, L1-13, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'New',
    action: 'Assign Tenant Coordinator',
    phase: 'New & Unassigned',
    caseStatus: 'on track',
    pendingWith: 'Contractor',
    isExpanded: false,
    isAssignedToUser: true,
    pendingWithName: 'Harry Porter',
  },
  {
    id: '2',
    caseNo: '50',
    property: 'The Second Mall of UAE',
    tenant: 'Alshaya (Debenhams)',
    units: 'LG-302, LG-303, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'Request',
    action: 'Assign Tenant Coordinator',
    phase: 'New & Unassigned',
    caseStatus: 'cancelled',
    pendingWith: 'Owner',
    isExpanded: false,
    isAssignedToUser: false,
    pendingWithName: 'Hermine Granger',
  },
  {
    id: '3',
    caseNo: '34',
    property: 'The Mall of UAE',
    tenant: 'Alshaya (Debenhams)',
    units: 'GF-302, GF-303',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'Submit',
    action: 'Approve MEP Detailed Design',
    phase: 'Design',
    caseStatus: 'on hold',
    pendingWith: 'Owner',
    isExpanded: false,
    isAssignedToUser: false,
    pendingWithName: 'Tom Wiesely',
  },
  {
    id: '4',
    caseNo: '87',
    property: 'The Second Mall of UAE',
    tenant: 'Landmark (Steve Madden)',
    units: 'L1-11, L1-13, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'New',
    action: 'Conduct General Inspection (3rd party)',
    phase: 'Unit Handover & Fitout ',
    caseStatus: 'delayed',
    pendingWith: 'Owner',
    isExpanded: false,
    isAssignedToUser: false,
    pendingWithName: 'Dumbubledore',
  },
  {
    id: '5',
    caseNo: '249',
    property: 'The Mall of UAE',
    tenant: 'Landmark (Centerpoint)',
    units: 'L1-11, L1-13, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'New',
    action: 'Assign Tenant Coordinator',
    phase: 'New & Unassigned',
    caseStatus: 'on track',
    pendingWith: 'Owner',
    isExpanded: false,
    isAssignedToUser: true,
    pendingWithName: 'Harry Porter',
  },
  {
    id: '6',
    caseNo: '510',
    property: 'The Second Mall of UAE',
    tenant: 'Alshaya (Debenhams)',
    units: 'LG-302, LG-303, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'Request',
    action: 'Assign Tenant Coordinator',
    phase: 'New & Unassigned',
    caseStatus: 'on track',
    pendingWith: 'Owner',
    isExpanded: false,
    isAssignedToUser: true,
    pendingWithName: 'Harry Porter',
  },
  {
    id: '7',
    caseNo: '7',
    property: 'The Mall of UAE',
    tenant: 'Alshaya (Debenhams)',
    units: 'GF-302, GF-303',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'Submit',
    action: 'Approve MEP Detailed Design',
    phase: 'Design',
    caseStatus: 'delayed',
    pendingWith: 'Contractor',
    isExpanded: false,
    isAssignedToUser: true,
    pendingWithName: 'Harry Porter',
  },
  {
    id: '8',
    caseNo: '65',
    property: 'The Second Mall of UAE',
    tenant: 'Landmark (Steve Madden)',
    units: 'L1-11, L1-13, L1-12, L1-14',
    taskDueDate: '5-Nov-2019',
    taskStatus: 'New',
    action: 'Conduct General Inspection (3rd party)',
    phase: 'Unit Handover & Fitout ',
    caseStatus: 'delayed',
    pendingWith: 'Tenant',
    isExpanded: false,
    isAssignedToUser: true,
    pendingWithName: 'Harry Porter',
  },
  // {
  //   id: '9',
  //   caseNo: '7',
  //   property: 'The Mall of UAE',
  //   tenant: 'Alshaya(Debenhams)',
  //   units: 'GF-302, GF-303',
  //   taskDueDate: '5-Nov-2019',
  //   taskStatus: 'Submit',
  //   action: 'Approve MEP Detailed Design',
  //   phase: 'Design',
  //   caseStatus: 'delayed',
  //   pendingWith: 'Owner',
  // },
  // {
  //   id: '10',
  //   caseNo: '45',
  //   property: 'The Second Mall of UAE',
  //   tenant: 'Landmark(Steve Madden)',
  //   units: 'L1-11,L1-13,L1-12,L1-14',
  //   taskDueDate: '5-Nov-2019',
  //   taskStatus: 'New',
  //   action: 'Conduct General Inspection (3rd party)',
  //   phase: 'Unit Handover & Fitout ',
  //   caseStatus: 'delayed',
  //   pendingWith: 'Owner',
  // },
  // {
  //   id: '11',
  //   caseNo: '11',
  //   property: 'The Mall of UAE',
  //   tenant: 'Alshaya(Debenhams)',
  //   units: 'GF-302, GF-303',
  //   taskDueDate: '5-Nov-2019',
  //   taskStatus: 'Submit',
  //   action: 'Approve MEP Detailed Design',
  //   phase: 'Design',
  //   caseStatus: 'delayed',
  //   pendingWith: 'Owner',
  // },
  // {
  //   id: '12',
  //   caseNo: '60',
  //   property: 'The Second Mall of UAE',
  //   tenant: 'Landmark(Steve Madden)',
  //   units: 'L1-11,L1-13,L1-12,L1-14',
  //   taskDueDate: '5-Nov-2019',
  //   taskStatus: 'New',
  //   action: 'Conduct General Inspection (3rd party)',
  //   phase: 'Unit Handover & Fitout ',
  //   caseStatus: 'delayed',
  //   pendingWith: 'Owner',
  // },
];

export const propertyList = [
  { id: '1', value: 'Property1' },
  { id: '2', value: 'Property2' },
];
export const customerList = [
  { id: '1', value: 'Customer1' },
  { id: '2', value: 'Customer2' },
];
export const brandList = [
  { id: '1', value: 'Brand1' },
  { id: '2', value: 'Brand2' },
];
export const unitsList = [
  { id: '1', value: 'Unit1' },
  { id: '2', value: 'Unit2' },
];
export const propertyPhaseList = [
  { id: '1', value: 'Phase1' },
  { id: '2', value: 'Phase2' },
];
export const caseTypeList = [
  { id: '1', value: 'CaseType1' },
  { id: '2', value: 'CaseType2' },
];
export const caseStatusList = [
  { id: '1', value: 'Status1' },
  { id: '2', value: 'Status2' },
];
export const assignedToUserList = [
  { id: '1', value: 'User1' },
  { id: '2', value: 'User2' },
];
