export const Selectrequisite = [
  {
    id: 0,
    value: 'Design Pre-requisite',
    status: '',
  },
  {
    id: 1,
    value: 'Design Pre-requisite',
    status: '',
  },
  {
    id: 2,
    value: 'Design Pre-requisite',
    status: '',
  },
];
export const Addrequisite = [
  {
    id: 0,
    value: 'Design - Inital Concept Design',
    status: '',
  },
  {
    id: 1,
    value: 'Design - Preliminary Design',
    status: '',
  },
  {
    id: 2,
    value: 'Design - Final Design',
    status: '',
  },

  {
    id: 3,
    value: 'Unit Handover & Fitout - Unit Handover', // and Sign off
    status: '',
  },
];
export const Phases = [
  {
    phaseId: '0653ca90-0335-4191-bfbf-da8fb98528d2',
    phaseName: 'kick-off',
    phaseSequence: 2,
    isMandatory: true,
    isParallel: false,
    phaseTypeId: 1,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: 'dc19b3ba-8683-4cb0-a6da-9e820162163d',
    phaseName: 'design',
    phaseSequence: 5,
    isMandatory: false,
    isParallel: true,
    phaseTypeId: 3,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: 'dd827259-5d4c-4b82-86c3-f62ec5f41349',
    phaseName: 'closure',
    phaseSequence: 8,
    isMandatory: true,
    isParallel: false,
    phaseTypeId: 2,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: '6cbdb20d-8876-4029-a53d-9358c1a57eb9',
    phaseName: 'unit handover & fitout',
    phaseSequence: 6,
    isMandatory: false,
    isParallel: false,
    phaseTypeId: 4,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: '65a58297-1f14-4fc0-90ca-400ad9415b0c',
    phaseName: 'landlord works',
    phaseSequence: 4,
    isMandatory: false,
    isParallel: true,
    phaseTypeId: 1,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: '519ae55f-1f67-40aa-80ec-a281e35c12ec',
    phaseName: 'new & unassigned',
    phaseSequence: 1,
    isMandatory: true,
    isParallel: false,
    phaseTypeId: 1,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: '374c426e-eb84-4861-bbe4-8c815683f692',
    phaseName: 'set-up workflow',
    phaseSequence: 3,
    isMandatory: true,
    isParallel: false,
    phaseTypeId: 1,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
  {
    phaseId: '6a6fd97b-56e7-49ae-9741-d3dd5629b11d',
    phaseName: 'unit opening',
    phaseSequence: 7,
    isMandatory: false,
    isParallel: false,
    phaseTypeId: 4,
    propertyPhasesId: null,
    propertyPhasesDetails: [],
    labels: [],
  },
];
