export const admin = [
  '/',
  '/forgotpassword',
  '/changepassword',
  '/accio/',
  '/department-and-roles',
  '/user-and-access',
  '/user-and-access/user-and-access-setup/:userId?',
  '/phases-and-more',
  '/phases-and-more/add-or-update-phases',
  '/phases-and-more/add-or-update-sub-phases',
  '/phases-and-more/add-update-pre-requisites-listing',
  '/phases-and-more/add-update-pre-requisites-groups-listing',
  '/phases-and-more/add-update-pre-requisites-listing/add-update-prerequisite/:prerequisiteId?',
  '/phases-and-more/add-update-pre-requisites-groups-listing/add-update-prerequisite-group/:prerequisiteGroupId?',
  '/workflows',
  '/setup-new-workflow/',
  '/setup-workflow/:id',
  '/setup-workflow/',
  '/design-forms',
  '/design-forms/setup-design-form/',
  '/design-forms/setup-design-form/:id',
];

export const business = [
  '/accio/',
  '/kick-off/users/types',
  '/kick-off/team',
  '/kick-off/users/roles?uType=',
  '/kick-off/users?roleRefId=',
  '/kick-off/assign-tenant-cordinator/',
  '/kick-off/kick-off-meeting-and-sign-off/',
  '/kick-off/kick-off-sign-off',
  '/kick-off',
  '/kick-off/Assign-owner-team-members',
  '/kick-off/assign-tenant-team-members',
  '/kick-off/add-or-Update-milestones',
  '/kick-off/schedule-kick-off-meeting',
  '/kick-off/kick-off-Meeting-sign-off',
  '/case-details',
  '/setup-workflow',
  '/design',
  '/design/initial-concept-design',
  '/design/preliminary-design',
  '/design/final-design',
  '/design/mep-detailed-design',
  '/design/close-design-phase',
  '/pre-requisites',
  '/unit-handover-fitout',
  '/unit-handover-fitout/unit-handover-and-sign-off',
  '/unit-handover-fitout/general-inspection-3rd-party',
  '/unit-handover-fitout/architectural-inspection',
  '/unit-handover-fitout/mep-inspection',
  '/unit-handover-fitout/fire-inspection',
  '/unit-handover-fitout/final-inspection',
  '/unit-handover-fitout/close-unit-handover-and-fitout',
  '/unit-opening',
  '/unit-opening/risk-security-inspection',
  '/unit-opening/health-and-safety-inspection',
  '/unit-opening/seek-approval-to-trade',
  '/unit-opening/close-unit-opening',
  '/closure',
  '/closure/final-pending-snag-list-check',
  '/closure/close-case',
];

export const Routesidebar = [
  {
    add_owner_team_screen: '',
    setup_workflow_screen: '',
    request_inspection_screen: '',
    conduct_inspection_screen: '',
    complete_inspection_screen: '',
    close_phase: '',
    landlordworks_completed_screen: '',

    submit_design_screen: '',
    review_design_screen: '',
    // submit_design_screen: '',
    approve_design_screen: '',
    design_completed_screen: '',
    schedule_fitout_meeting: '',
    unit_handover_meeting_signoff: '',
    // request_inspection_screen: '',
    // conduct_inspection_screen: '',
    // complete_inspection_screen: '',
    // close_phase: '',

    unit_handover_and_fitout_completed_screen: '',
    // combination : action
    assign_snaglist: '',
    action_snaglist: '',
    reject_snaglist: '',
    complete_snaglist: '',
    send_for_approval: '',
    action_sent_for_approval: '',

    // request_inspection_screen: '',
    // conduct_inspection_screen: '',
    // complete_inspection_screen: '',
    // send_for_approval: '',
    // close_phase: '',

    unit_opening_completed_screen: '',

    // request_inspection_screen: '',
    // conduct_inspection_screen: '',
    // complete_inspection_screen: '',
    close_case_screen: '',

    fitout_closure_completed_screen: '',
    // add_owner_team_screen: '',
    add_tenant_team_screen: '',
    add_update_milestone_screen: '',
    schedule_kickoff_meeting_screen: '',
    kickoff_meeting_and_singoff_screen: '',

    // if user type is tenant do not see subphase directly return below value
    kickoff_tenant_screen_user_contractor: '',
  },
];
