// header
export const SET_USER_PROPERTIES = 'SET_USER_PROPERTIES';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_PROP_APP_STATUS = 'SET_PROP_APP_STATUS';

export const SET_USER_LANGUAGES = 'SET_USER_LANGUAGES';
export const SET_PRIMARY_LANGUAGE = 'SET_PRIMARY_LANGUAGE';

// TOGGLE_SIDEBAR
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';

// BUSSINES SIDEBAR
export const SET_SIDEBAR_DATA = 'SET_SIDEBAR_DATA';

/** RESET */
export const RESET = 'RESET';
export const RESET_WORKFLOW = 'RESET_WORKFLOW';
export const RESET_WORKFLOW_FORM = 'RESET_WORKFLOW_FORM';
/* Prerequiste */
export const SET_PREREQUISITE_LIST = 'SET_PREREQUISITE_LIST';
export const SET_PREREQUISITE_LIST_LOADING = 'SET_PREREQUISITE_LIST_LOADING';
export const SET_TOTAL_LIST_COUNT = 'SET_TOTAL_LIST_COUNT';
export const SET_PREREQUISITE_DETAILS = 'SET_PREREQUISITE_DETAILS';
export const SET_PREREQUISITE_FIELDS = 'SET_PREREQUISITE_FIELDS';
/* Prerequisite Group */
export const SET_PREREQUISITE_GROUP_LIST = 'SET_PREREQUISITE_GROUP_LIST';
export const ADD_PREREQUISITE_TO_GROUP = 'ADD_PREREQUISITE_TO_GROUP';
export const SET_TOTAL_GROUPLIST_COUNT = 'SET_TOTAL_GROUPLIST_COUNT';
export const SET_PREREQUISITE_GROUP_LIST_LOADING =
  'SET_PREREQUISITE_GROUP_LIST_LOADING';
/** WORKFLOWS */
export const SET_WORKFLOW_LIST = 'SET_WORKFLOW_LIST';
export const SET_WORKFLOW_LIST_LOADING = 'SET_WORKFLOW_LIST_LOADING';

/** Setup WorkFlow */
export const SET_WIZARD_STEPS = 'SET_WIZARD_STEPS';
// export const SET_WORKFLOW_LIST = 'SET_WORKFLOW_LIST';
export const SETUP_WORKFLOW_LOADING = 'SETUP_WORKFLOW_LOADING';
export const SET_DEFAULT_STATE = 'SET_DEFAULT_STATE';
export const SET_LANGAUGES = 'SET_LANGAUGES';
export const SET_WORKFLOW_IS_MODIFY = 'SET_WORKFLOW_IS_MODIFY';

/** STEP 1 */
export const SET_FITOUT_TYPES_LIST = 'SET_FITOUT_TYPES_LIST';

/**
 * PHASES AND MORE
 *   ADD OR UPDATE PHASES
 *      GET PHASES LIST
 *
 *   ADD OR UPDATE SUB-PHASES
 *
 * */

// GET PHASES LIST
export const GET_PHASES_LIST_REQUEST = 'GET_PHASES_LIST_REQUEST';
export const GET_PHASES_LIST_RESPONSE = 'GET_PHASES_LIST_RESPONSE';
export const GET_PHASES_LIST_ERROR = 'GET_PHASES_LIST_ERROR';

// SAVE_PHASES_LIST_REQUEST
export const SAVE_PHASES_LIST_REQUEST = 'SAVE_PHASES_LIST_REQUEST';
export const SAVE_PHASES_LIST_RESPONSE = 'SAVE_PHASES_LIST_RESPONSE';
export const SAVE_PHASES_LIST_ERROR = 'SAVE_PHASES_LIST_ERROR';
export const SET_IS_SAVED_PHASES = 'SET_IS_SAVED_PHASES';

/** STEP 2 */
export const SET_PHASES_LIST_IN_WIZARD = 'SET_PHASES_LIST_IN_WIZARD';
export const SET_PHASES_LIST_LOADING = 'SET_PHASES_LIST_LOADING';

/** STEP 3 */
export const SET_SUB_PHASES_LIST_IN_WIZARD = 'SET_SUB_PHASES_LIST_IN_WIZARD';
export const SET_SUB_PHASES_LIST_LOADING = 'SET_SUB_PHASES_LIST_LOADING';

/** STEP 4 */
export const SET_PRE_REQUISITE_LIST = 'SET_PRE_REQUISITE_LIST';
export const SET_SELECT_PRE_REQUISITE_LIST = 'SET_SELECT_PRE_REQUISITE_LIST';
// export const SET_ADD_PRE_REQUISITE_LIST = 'SET_ADD_PRE_REQUISITE_LIST';
export const SET_PRE_REQUISITE_LIST_IN_WIZARD =
  'SET_PRE_REQUISITE_LIST_IN_WIZARD';

/**
 * Design Forms
 */

export const SET_FORM_WIZARD_STEPS = 'SET_FORM_WIZARD_STEPS';
export const SET_IS_FORM_LOADING = 'SET_IS_FORM_LOADING';
export const RESET_DESIGN_FORM = 'RESET_DESIGN_FORM';

// set forms list
export const SET_FORMS_LIST = 'SET_FORMS_LIST';
export const SET_FORMS_LIST_LOADING = 'SET_FORMS_LIST_LOADING';
export const SET_DESIGN_SUBPHASES_LIST = 'SET_DESIGN_SUBPHASES_LIST';
export const SET_FITOUT_TYPES_DESING_FORM_LIST =
  'SET_FITOUT_TYPES_DESING_FORM_LIST';

export const SET_FORMS_WIZARD_STEPS = 'SET_FORMS_WIZARD_STEPS';

// step 1
export const SET_FORM_ID = 'SET_FORM_ID';

// step 4
export const SET_FILE_TYPES_LIST = 'SET_FILE_TYPES_LIST';

// to set form data in design form
export const SET_FORM_DATA = 'SET_FORM_DATA';

// User and Access
export const SET_WIZARD_STEPS_USER_ACCESS = 'SET_WIZARD_STEPS_USER_ACCESS';
export const SET_COMPANY_LIST = 'SET_COMPANY_LIST';
export const SET_LLC_LIST = 'SET_LLC_LIST';
export const SET_PROPERTY_LIST = 'SET_PROPERTY_LIST';
export const SET_CUSTOMER_LIST = 'SET_CUSTOMER_LIST';
export const SET_BRAND_TYPE_LIST = 'SET_BRAND_TYPE_LIST';
export const SET_BRAND_LIST = 'SET_BRAND_LIST';
export const SET_SELECTED_PROPERTY_LIST = 'SET_SELECTED_PROPERTY_LIST';
export const SET_ROLES_LIST = 'SET_ROLES_LIST';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_USER_LIST_IS_LOADING = 'SET_USER_LIST_IS_LOADING';
export const SET_USER_LIST_COUNT = 'SET_USER_LIST_COUNT';
export const SET_USER_TYPE_LIST = 'SET_USER_TYPE_LIST';
export const SET_ASSIGNED_ACCESS = 'SET_ASSIGNED_ACCESS';
export const SET_ASSIGNED_CUSTOMER = 'SET_ASSIGNED_CUSTOMER';
export const SET_ASSIGNED_DEPARTMENT = 'SET_ASSIGNED_DEPARTMENT';
export const SET_USER_ACCESS_TYPE_LIST = 'SET_USER_ACCESS_TYPE_LIST';
export const SET_USER_ID = 'SET_USER_ID';
export const RESET_USERDATA_TO_INITIAL_STATE =
  'RESET_USERDATA_TO_INITIAL_STATE';

/** Business Application */
/** Case Listing or Dashboard */
export const GET_PHASEWISE_CASE_DETAILS = 'GET_PHASEWISE_CASE_DETAILS';
export const SET_CASE_LIST_DETAILS = 'SET_CASE_LIST_DETAILS';
export const SET_CASE_LIST_DETAILS_TOTAL = 'SET_CASE_LIST_DETAILS_TOTAL';
export const SET_CASE_LIST_DETAILS_IS_LOADING =
  'SET_CASE_LIST_DETAILS_IS_LOADING';
export const SET_USER_ACCESS_PROPERTIES = 'SET_USER_ACCESS_PROPERTIES';
export const SET_CUSTOMER_FILTER_LIST = 'SET_CUSTOMER_FILTER_LIST';
export const SET_BRAND_FILTER_LIST = 'SET_BRAND_FILTER_LIST';
export const SET_UNITS_LIST = 'SET_UNITS_LIST';
export const SET_CASE_STATUS_LIST = 'SET_CASE_STATUS_LIST';
export const SET_PROPERTY_PHASE_LIST = 'SET_PROPERTY_PHASE_LIST';
export const SET_CASE_TYPE_LIST = 'SET_CASE_TYPE_LIST';
export const SET_ASSIGNED_TO_USER_LIST = 'SET_ASSIGNED_TO_USER_LIST';
export const SET_IS_CASE_MANIPULATION_ACCESS =
  'SET_IS_CASE_MANIPULATION_ACCESS';

export const SET_IS_ALL_PROPERTY_LICENSE_SUSPENDED =
  'SET_IS_ALL_PROPERTY_LICENSE_SUSPENDED';

/** Case Details */

export const SET_USER_PROPERTY_LIST_WITH_CM_ACCESS =
  'SET_USER_PROPERTY_LIST_WITH_CM_ACCESS';
export const SET_CUSTOMER_LIST_CASE_DETAILS = 'SET_CUSTOMER_LIST_CASE_DETAILS';
export const SET_BRNAD_LIST_CASE_DETAILS = 'SET_BRNAD_LIST_CASE_DETAILS';
export const SET_AMENDMENT_TYPE_LIST = 'SET_AMENDMENT_TYPE_LIST';

/* Date Picker */
/* specialDatesAction,
  publicHolidayDatesAction,
  weekEndAction, */

export const SET_SPECIAL_DATE = 'SET_SPECIAL_DATE';
export const SET_SPECIAL_EVENTS_DATE = 'SET_SPECIAL_EVENTS_DATE';
export const SET_PUBLIC_HOLIDAY = 'SET_PUBLIC_HOLIDAY';
export const SET_WEEK_END = 'SET_WEEK_END';
export const SET_DATE_PICKER_API_CALLING = 'SET_DATE_PICKER_API_CALLING';

/* Add Update Milestones */

export const SET_PHASE_LISTING_TABLE = 'SET_PHASE_LISTING_TABLE';
export const SET_PHASE_LISTING_TABLE_BACKUP = 'SET_PHASE_LISTING_TABLE_BACKUP';
export const SET_SELECT_WORKFLOW_LIST = 'SET_SELECT_WORKFLOW_LIST';
export const GET_SCHEDULE_MEETING_EMAILS = 'GET_SCHEDULE_MEETING_EMAILS';
